apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-flask-hello-fbi2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-flask-hello-fbi2
    app.kubernetes.io/part-of: p
  name: python-flask-hello-fbi2
  namespace: burrzinga-hac-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-flask-hello-fbi2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-flask-hello-fbi2
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/burrzinga-hac-tenant/p/python-flask-hello-fbi2@sha256:75bf3b37dfece5b461dd0ada12af78a7f8149fa051f3a6e3a54a8576922c3bb3
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
